
typedef enum _tGameUIGadget {
    GAME_UI_GADGET_NONE,
    GAME_UI_GADGET_MENU,
    GAME_UI_GADGET_MAP,
    GAME_UI_GADGET_TEXTFIELD,
    GAME_UI_GADGET_VIEWPORT,
    GAME_UI_GADGET_FORWARD,
    GAME_UI_GADGET_BACKWARD,
    GAME_UI_GADGET_LEFT,
    GAME_UI_GADGET_RIGHT,
    GAME_UI_GADGET_TURN_LEFT,
    GAME_UI_GADGET_TURN_RIGHT,
    GAME_UI_GADGET_BATTERY,
    GAME_UI_GADGET_INV_UP,
    GAME_UI_GADGET_INV_DOWN,
    GAME_UI_GADGET_INV_SLOT_1,
    GAME_UI_GADGET_INV_SLOT_2,
    GAME_UI_GADGET_INV_SLOT_3,
    GAME_UI_GADGET_INV_SLOT_4,
    GAME_UI_GADGET_INV_SLOT_5,
    GAME_UI_GADGET_INV_SLOT_6,
    GAME_UI_GADGET_EQUIPMENT_1,
    GAME_UI_GADGET_EQUIPMENT_2,
    GAME_UI_GADGET_EQUIPMENT_3,
    GAME_UI_GADGET_EQUIPMENT_4,
    GAME_UI_GADGET_MAX
} tGameUIGadget;

typedef enum _tViewportUIGadgets  {
    VIEWPORT_UI_GADGET_NONE = GAME_UI_GADGET_MAX+1,
    VIEWPORT_UI_GADGET_FORWARD,
    VIEWPORT_UI_GADGET_BACKWARD,
    VIEWPORT_UI_GADGET_LEFT,
    VIEWPORT_UI_GADGET_RIGHT,
    VIEWPORT_UI_GADGET_TURN_LEFT,
    VIEWPORT_UI_GADGET_TURN_RIGHT,
    VIEWPORT_UI_GADGET_FLOOR,
    VIEWPORT_UI_GADGET_DOOR_BUTTON,
    VIEWPORT_UI_GADGET_DOOR,
    VIEWPORT_UI_GADGET_WALL,
    VIEWPORT_UI_GADGET_MAX
} tViewportUIGadgets;


