#include "maze.h"
/*
;  E6   ENCOUNTER
;  E7   IDENTIFYITEMS
;  E8   TURN
;  E9   LAUNCHER
;  EA   ADD_ITEM
;  EB   GIVE_XP
;  EC   CHANGE_LEVEL
;  ED   REMOVE_ITEM
;  EE   IF
;  EF   GOSUB
;  F0   RETURN
;  F1   END
;  F2   GOTO
;  F3   DAMAGE
;  F5   CLEAR_FLAG
;  F6   SOUND
;  F7   SET_FLAG
;  F8   MESSAGE
;  F9   STEAL_ITEM
;  FA   TELEPORT
;  FB   ADD_MONSTER
;  FC   CLOSE_DOOR
;  FD   OPEN_DOOR
;  FE   CHANGE_WALL
;  FF   SET_WALL

; IF () BLOCK PARAMETERS
; ======================
;  DA   PARTY_VISIBLE
;  DB   ROLL_DICE
;  DC   HAS_CLASS
;  DD   HAS_RACE
;  E0   TRIGGER_FLAG
;  E7   POINTER_ITEM
;  E9   WALL_SIDE
;  ED   PARTY_DIRECTION
;  EE   ELSE_GOTO
;  EF   LEVEL_FLAG
;  F0   GLOBAL_FLAG
;  F1   PARTY_ON_POS
;  F3   MONSTERS_ON_POS
;  F5   ITEMS_ON_POS
;  F7   WALL_NUMBER
;  F8   OR
;  F9   AND
;  FB   >
;  FD   <
;  FE   <>
;  FF   =
*/
#define EVENT_SETWALL 0
#define EVENT_SETFLOOR 1
#define EVENT_SETCOL 2
#define EVENT_CLEARWALL 3
#define EVENT_CLEARFLOOR 4
#define EVENT_CLEARCOL 5
#define EVENT_SETWALLCOL 6
#define EVENT_CLEARWALLCOL 7
#define EVENT_SHOWMESSAGE 8
#define EVENT_OPENDOOR 9
#define EVENT_CLOSEDOOR 10

#define EVENT_TELEPORT 11
#define EVENT_GIVEITEM 12
#define EVENT_TAKEITEM 13
#define EVENT_SETFLAG 14
#define EVENT_CLEARFLAG 15

#define EVENT_ADDMONSTER 16
#define EVENT_REMOVEMONSTER 17
#define EVENT_ADDITEM 18
#define EVENT_REMOVEITEM 19
#define EVENT_ADDXP 20
#define EVENT_DAMAGE 21
#define EVENT_LAUNCHER 22
#define EVENT_TURN 23
#define EVENT_IDENTIFYITEMS 24
#define EVENT_ENCOUNTER 25
#define EVENT_SOUND 26

#define EVENT_IF 128
#define EVENT_ELSE 129
#define EVENT_ENDIF 130
#define EVENT_GOTO 131
#define EVENT_GOSUB 132
#define EVENT_RETURN 133

#define EVENT_PARTY_VISIBLE 200
#define EVENT_ROLL_DICE 201
#define EVENT_HAS_CLASS 202
#define EVENT_HAS_RACE 203
#define EVENT_TRIGGER_FLAG 204
#define EVENT_POINTER_ITEM 205
#define EVENT_WALL_SIDE 206
#define EVENT_PARTY_DIRECTION 207
#define EVENT_ELSE_GOTO 208
#define EVENT_LEVEL_FLAG 209
#define EVENT_GLOBAL_FLAG 210
#define EVENT_PARTY_ON_POS 211
#define EVENT_MONSTERS_ON_POS 212
#define EVENT_ITEMS_ON_POS 213
#define EVENT_WALL_NUMBER 214
#define EVENT_OR 215
#define EVENT_AND 216
#define EVENT_GREATER 217
#define EVENT_LESS 218
#define EVENT_NOT_EQUAL 219
#define EVENT_EQUAL 220

void handleEvent(tMaze *pMaze, tMazeEvent *pEvent);