//This file is automatically generated by build_number.cmake

#ifndef __BUILD_NUMBER_H__INCLUDED__
#define __BUILD_NUMBER_H__INCLUDED__

#define VERSION_MAJOR 
#define VERSION_MINOR 
#define VERSION_PATCH 2512
#define VERSION_BUILD 295
#define VERSION_STRING "1.2.2512.295"

#endif