//This file is automatically generated by build_number.cmake

#ifndef __BUILD_NUMBER_H__INCLUDED__
#define __BUILD_NUMBER_H__INCLUDED__

#define VERSION_MAJOR 
#define VERSION_MINOR 
#define VERSION_PATCH 2602
#define VERSION_BUILD 321
#define VERSION_STRING "1.2.2602.321"

#endif